version: '3.6'
services:
    #postgres init
    db:
      build:
          context: ./facadservice/db/
          dockerfile: Dockerfile
      image: postgres
      container_name: postgresge
      ports:
        - 5432:5432 
      volumes:
        - ./my-vol:/data
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRESS_DB: userdb
      restart: always
      networks:
        - localnetwork
    
    #cassandra init
    cassandra:
      build:
          context: ./tseriesservice/cassandra/
          dockerfile: Dockerfile
      container_name: cassandrage
      ports:
        - 9042:9042
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
      networks:
        - localnetwork
        
    #kafka init, depends on zookeeper
    zookeeper:
      image: wurstmeister/zookeeper:3.4.6
      container_name: zookeeperge
      expose:
        - 2181
      networks:
        - localnetwork
        
    kafka:
      image: wurstmeister/kafka:2.11-2.0.0
      container_name: kafkage
      depends_on:
        - zookeeper
      ports:
        - 9092:9092
      environment:
        KAFKA_CREATE_TOPICS: "data_topic:1:1,notification_topic:1:1"
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkage:9092
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      networks:
        - localnetwork    
    
    #file processor service init
    fileprocsrv:
        build:
            context: ./fileprocservice/
            dockerfile: Dockerfile
        image: fileprocservice
        container_name: fileprocservicege
        ports:
          - 8081:8081
        volumes:
          - ./my-vol:/data
        restart: always
        networks:
          - localnetwork
        
    #tseries service init
    tseriessrv:
        build:
            context: ./tseriesservice/
            dockerfile: Dockerfile
        image: tseriesservice
        container_name: tseriesservicege
        ports:
          - 8082:8082
        environment:
            SPRING_DATA_CASSANDRA_CONTACT_POINTS: cassandra
        restart: always
        depends_on: 
          - cassandra
        networks:
          - localnetwork
        
    #event service init
    eventsrv:
        build:
            context: ./eventservice/
            dockerfile: Dockerfile
        image: eventservice
        container_name: eventservicege
        ports:
          - 8083:8083
        restart: always
        networks:
          - localnetwork
        
    #stat service init
    statsrv:
        build:
            context: ./statservice/
            dockerfile: Dockerfile
        image: statservice
        container_name: statservicege
        ports:
          - 8084:8084
        environment:
            SPRING_DATA_CASSANDRA_CONTACT_POINTS: cassandra
        restart: always
        depends_on: 
          - cassandra
        networks:
          - localnetwork
        
    #facad service init
    facadsrv:
        build:
            context: ./facadservice/
            dockerfile: Dockerfile
        image: facadservice
        container_name: facadservicege
        ports:
          - 8085:8085
        environment:
            POSTGRESS_HOST: db
        restart: always
        depends_on: 
          - db
        networks:
          - localnetwork          
          
networks:
    localnetwork: