version: '3.6'
services:
    #postgres init
    db:
      build:
          context: ./facadservice/db/
          dockerfile: Dockerfile
      image: postgres
      container_name: postgres_ge
      ports:
        - 5432:5432 
      volumes:
        - ./my-vol:/data
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRESS_DB: userdb
      restart: always
    
    #cassandra init
    cassandra:
      image: cassandra:latest
      container_name: cassandra_ge
      ports:
        - 9042:9042
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
    
    #kafka init, depends on zookeeper
    zookeeper:
      image: wurstmeister/zookeeper:3.4.6
      container_name: zookeeper_ge
      expose:
        - 2181

    kafka:
      image: wurstmeister/kafka:2.11-2.0.0
      container_name: kafka_ge
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        
    #file processor service init
    fileprocsrv:
        build:
            context: ./fileprocservice/
            dockerfile: Dockerfile
        image: fileprocservice
        container_name: fileprocservice_ge
        ports:
          - "8081:8081"
        restart: always
        
    #tseries service init
    tseriessrv:
        build:
            context: ./tseriesservice/
            dockerfile: Dockerfile
        image: tseriesservice
        container_name: tseriesservice_ge
        ports:
          - "8082:8082"
        restart: always
        
    #event service init
    eventsrv:
        build:
            context: ./eventservice/
            dockerfile: Dockerfile
        image: eventservice
        container_name: eventservice_ge
        ports:
          - "8083:8083"
        restart: always
        
    #stat service init
    #statsrv:
    #    build:
    #        context: ./statservice/
    #        dockerfile: Dockerfile
    #    image: statservice
    #    container_name: statservice_ge
    #    ports:
    #      - "8084:8084"
    #    restart: always
        
    #facad service init
    facadsrv:
        build:
            context: ./facadservice/
            dockerfile: Dockerfile
        image: facadservice
        container_name: facadservice_ge
        ports:
          - "8085:8085"
        environment:
            POSTGRESS_HOST: db 
        restart: always
        links: 
          - db  